# Generated by Django 5.0.1 on 2026-01-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('declaracao_militar', 'Declaração Militar'), ('cedula_militar', 'Cédula Militar'), ('recibo_recenseamento', 'Recibo de Recenseamento Militar')], max_length=50)),
                ('destino', models.CharField(blank=True, max_length=200, null=True)),
                ('finalidade', models.CharField(blank=True, max_length=200, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('numero_sequencial', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
