# Generated by Django 5.0.1 on 2026-01-15 06:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCidadao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bi', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='bi')),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto')),
                ('dados_confirmados', models.BooleanField(default=False)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nome_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_bi', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('acao_completada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recenseamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bi', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('data_nascimento', models.DateField()),
                ('nim', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nome_completo', models.CharField(max_length=150)),
                ('filiacao_pai', models.CharField(max_length=150)),
                ('filiacao_mae', models.CharField(max_length=150)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('naturalidade', models.CharField(max_length=100)),
                ('morada', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contacto_familiar', models.CharField(max_length=150)),
                ('documento_identidade', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='documento_identidade')),
                ('foto_capturada', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_capturada')),
                ('foi_submetido_exame', models.BooleanField(blank=True, null=True)),
                ('resultado_exame', models.CharField(blank=True, choices=[('apto', 'Apto'), ('inapto', 'Inapto')], max_length=10, null=True)),
            ],
        ),
    ]
