# Generated by Django 5.1.5 on 2025-12-26 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCidadao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bi', models.FileField(blank=True, null=True, upload_to='documentos/bi/')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil_fotos/')),
                ('dados_confirmados', models.BooleanField(default=False)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nome_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_bi', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recenseamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bi', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('data_nascimento', models.DateField()),
                ('nim', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nome_completo', models.CharField(max_length=150)),
                ('filiacao_pai', models.CharField(max_length=150)),
                ('filiacao_mae', models.CharField(max_length=150)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('naturalidade', models.CharField(max_length=100)),
                ('morada', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contacto_familiar', models.CharField(max_length=150)),
                ('documento_identidade', models.FileField(blank=True, null=True, upload_to='documentos_identidade_uploads/')),
                ('foto_capturada', models.ImageField(blank=True, null=True, upload_to='selfies/')),
                ('foi_submetido_exame', models.BooleanField(blank=True, null=True)),
                ('resultado_exame', models.CharField(blank=True, choices=[('apto', 'Apto'), ('inapto', 'Inapto')], max_length=10, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
