# Generated by Django 5.0.1 on 2026-01-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recenseamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcidadao',
            name='acao_completada',
            field=models.BooleanField(default=False),
        ),
    ]
