# Generated by Django 5.0.1 on 2026-01-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recenseamento', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcidadao',
            name='numero_bi',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
