# Generated by Django 5.0.1 on 2026-01-08 07:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recenseamento', '0002_perfilcidadao_acao_completada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcidadao',
            name='bi',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='bi'),
        ),
        migrations.AlterField(
            model_name='perfilcidadao',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='recenseamento',
            name='documento_identidade',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='documento_identidade'),
        ),
        migrations.AlterField(
            model_name='recenseamento',
            name='foto_capturada',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_capturada'),
        ),
    ]
