# Generated by Django 5.0.1 on 2026-01-10 01:57

import usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', usuarios.models.CustomUserManager()),
            ],
        ),
    ]
